# Generated by Django 5.2.17 on 2026-09-22 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_seed_pipeline_stages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zernio_conversation_id', models.CharField(max_length=200, unique=True, verbose_name='id de conversación en Zernio')),
                ('zernio_account_id', models.CharField(blank=True, max_length=200, verbose_name='id de cuenta en Zernio')),
                ('platform', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('messenger', 'Messenger')], max_length=20, verbose_name='plataforma')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='nombre de contacto')),
                ('contact_identifier', models.CharField(blank=True, max_length=200, verbose_name='identificador de contacto')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='última actividad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='crm.lead', verbose_name='lead')),
            ],
            options={
                'verbose_name': 'conversación',
                'verbose_name_plural': 'conversaciones',
                'ordering': ('-last_message_at',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zernio_message_id', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='id de mensaje en Zernio')),
                ('direction', models.CharField(choices=[('in', 'Entrante'), ('out', 'Saliente')], max_length=3, verbose_name='dirección')),
                ('text', models.TextField(blank=True, verbose_name='texto')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='recibido')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.conversation', verbose_name='conversación')),
            ],
            options={
                'verbose_name': 'mensaje',
                'verbose_name_plural': 'mensajes',
                'ordering': ('created_at',),
            },
        ),
    ]
