# Generated by Django 5.2.17 on 2026-09-22 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_conversation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('messenger', 'Messenger')], max_length=20, unique=True, verbose_name='plataforma')),
                ('enabled', models.BooleanField(default=False, verbose_name='activo')),
                ('system_prompt', models.TextField(blank=True, default='Sos el asistente de una inmobiliaria. Respondé breve y en español, ayudando a entender qué busca la persona (operación, zona, presupuesto). No inventes datos de propiedades.', verbose_name='prompt del sistema')),
                ('model', models.CharField(blank=True, help_text='Vacío usa el modelo por defecto (OPENAI_MODEL).', max_length=100, verbose_name='modelo')),
            ],
            options={
                'verbose_name': 'configuración del agente',
                'verbose_name_plural': 'configuraciones del agente',
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('event_id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='id de evento')),
                ('provider', models.CharField(default='zernio', max_length=20, verbose_name='proveedor')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='recibido')),
            ],
            options={
                'verbose_name': 'evento de webhook',
                'verbose_name_plural': 'eventos de webhook',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='ai_enabled',
            field=models.BooleanField(default=True, help_text='Apagalo para que un asesor tome el hilo a mano sin desactivar el canal entero.', verbose_name='IA activa en esta conversación'),
        ),
        migrations.AddField(
            model_name='message',
            name='ai_generated',
            field=models.BooleanField(default=False, verbose_name='generado por IA'),
        ),
        migrations.CreateModel(
            name='ContactIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('messenger', 'Messenger')], max_length=20, verbose_name='plataforma')),
                ('external_id', models.CharField(max_length=200, verbose_name='id externo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='crm.lead', verbose_name='lead')),
            ],
            options={
                'verbose_name': 'identidad de contacto',
                'verbose_name_plural': 'identidades de contacto',
                'constraints': [models.UniqueConstraint(fields=('platform', 'external_id'), name='unique_platform_external_id')],
            },
        ),
    ]
